FROM eristoddle/wso2dss:3.5.1

COPY /repository/conf/datasources/master-datasources.xml /mnt/wso2dss/repository/conf/datasources/master-datasources.xml
COPY /repository/conf/carbon.xml /mnt/wso2dss/repository/conf/carbon.xml
COPY /repository/conf/registry.xml /mnt/wso2dss/repository/conf/registry.xml
COPY /repository/conf/axis2/axis2.xml /mnt/wso2dss/repository/conf/axis2/axis2.xml
COPY /repository/conf/security/authenticators.xml /mnt/wso2dss/repository/conf/security/authenticators.xml
