FROM eristoddle/wso2greg:5.3.0

COPY /repository/conf/datasources/master-datasources.xml /mnt/wso2greg/repository/conf/datasources/master-datasources.xml
COPY /repository/conf/security/authenticators.xml /mnt/wso2greg/repository/conf/security/authenticators.xml
COPY /repository/conf/carbon.xml /mnt/wso2greg/repository/conf/carbon.xml
COPY /repository/conf/registry.xml /mnt/wso2greg/repository/conf/registry.xml
COPY /repository/conf/axis2/axis2.xml /mnt/wso2greg/repository/conf/axis2/axis2.xml
COPY /repository/resources/lifecycles/ServiceLifeCycle.xml /mnt/wso2greg/repository/resources/lifecycles/ServiceLifeCycle.xml
