FROM eristoddle/wso2esb:5.0.0

COPY /repository/conf/datasources/master-datasources.xml /mnt/wso2esb/repository/conf/datasources/master-datasources.xml
COPY /repository/conf/carbon.xml /mnt/wso2esb/repository/conf/carbon.xml
COPY /repository/conf/registry.xml /mnt/wso2esb/repository/conf/registry.xml
# COPY /repository/conf/axis2/axis2.xml /mnt/wso2esb/repository/conf/axis2/axis2.xml
COPY /repository/conf/security/authenticators.xml /mnt/wso2esb/repository/conf/security/authenticators.xml
