FROM eristoddle/wso2as:5.3.0

COPY /repository/conf/datasources/master-datasources.xml /mnt/wso2as/repository/conf/datasources/master-datasources.xml
COPY /repository/conf/carbon.xml /mnt/wso2as/repository/conf/carbon.xml
COPY /repository/conf/registry.xml /mnt/wso2as/repository/conf/registry.xml
COPY /repository/conf/axis2/axis2.xml /mnt/wso2as/repository/conf/axis2/axis2.xml
COPY /repository/conf/security/authenticators.xml /mnt/wso2as/repository/conf/security/authenticators.xml
