FROM busybox:latest
VOLUME ["/mnt"]
COPY build/prod/conf /tmp-conf
CMD mv -R /tmp-conf/wso2am/* /mnt/wso2am/
CMD mv -R /tmp-conf/wso2as/* /mnt/wso2as/
CMD mv -R /tmp-conf/wso2brs/* /mnt/wso2brs/
CMD mv -R /tmp-conf/wso2dss/* /mnt/wso2dss/
CMD mv -R /tmp-conf/wso2esb/* /mnt/wso2esb/
CMD mv -R /tmp-conf/wso2greg/* /mnt/wso2greg/
CMD mv -R /tmp-conf/wso2is/* /mnt/wso2is/

# Key to creating container for data
CMD ["true"]
